# Generated by Django 3.1.3 on 2021-06-09 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210606_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='avator',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
